### ISSUE TITLE
File in use by another process - Windows 10

### ISSUE THREAD

**Issue by Mal1t1a** [maxton/GameArchives#10]
Hey, I've been trying to read an .ARK file extracted from the Frequenecy.bin file. When I ran the program (as administrator as well), I go to open up the "LEVELS.ARK" file and I immediately get presented with a "File in use by another process" error. Obviously this error is very self explainitory, however I tried creating a copy of the file, moving the file to another computer and running this program as well. All bring fourth the same error. I'm running Windows 10 on both computers. I suspect it may be the program itself is causing the file to be locked at the same time it goes to read the file.

**Comment by maxton** [comment]
This should have been fixed in 0.11.2 but I tried LEVELS.ARK and it didn't work, so I will look into it
