### ISSUE TITLE
amplitude ps3 hdr/arks refuse to open

### ISSUE THREAD

**Issue by infinitephantasm** [maxton/GameArchives#11]
i can't seem to get any form of these opening on archiveexplorer. i ripped it from a pkg so i'm unsure if the rip is bad or if it simply can't recognize the format

**Comment by maxton** [comment]
I don't have any samples of arks for the PS3 version of amplitude, so it would only open if it's the same as another Ark version (which, evidently, it isn't). If you upload the hdr file I could probably add support.

**Comment by maxton** [comment]
Fixed in #12
