### ISSUE TITLE
Extracted moggs won't open in audacity

### ISSUE THREAD

**Issue by chr0m** [maxton/GameArchives#21]
I downloaded a collection of mogg files from Beatles Rock Band and they work great in Audacity.

I tried extracting my own using this tool, but they won't open in Audacity.
I tried opening the .hdr file in Beatles Rock Band on Xbox 360 and I can extract them fine, but Audacity won't recognise them.

Same result if I try to extract mogg files from DLC archives.

Am I doing something wrong or are these not supported?

**Comment by maxton** [comment]
This is beyond the scope of the project. Those files are likely encrypted.

**Comment by chr0m** [comment]
I guessed it was something liked that.

The files are also smaller than the ones I have that work.

Thanks for the reply
