### ISSUE TITLE
Can't use replace file option in editor

### ISSUE THREAD

**Issue by wintyre01** [maxton/GameArchives#27]
I'm trying to replace all of the moggs with my decensored versions of applicable songs in Dance Central 3, but when I find the files in the editor, the "Replace File" option is greyed out. I've tested with multiple games as well, including Rock Band 3

<img width="440" alt="Replace" src="https://github.com/maxton/GameArchives/assets/143204241/faee45a5-4707-4e10-8946-fa019b5a71a8">

**Comment by PikminGuts92** [comment]
Editing archives was a planned feature but maxton never got around to implementing functionality. Having said that, an alternative you can try is using `arkhelper` from [here](https://github.com/PikminGuts92/Mackiloha). DC3 arks are the same version as RB3 so you can use same command in README.

**Comment by wintyre01** [comment]
Yup I found it. Thanks!
