### ISSUE TITLE
Not all files listed in pfs_images

### ISSUE THREAD

**Issue by luxox8** [maxton/GameArchives#6]
if the index section of the pfs_image have some extra 00's between names, the tool will ignore all files that are after this block.

![empty](https://cloud.githubusercontent.com/assets/25025914/21797068/9ac98b88-d6eb-11e6-88fb-cb7aee58fc6f.jpg)

not all 00 sections have the same size that the showed in the image.

**Comment by maxton** [comment]
Yup, there are definitely some issues with PFS. Unfortunately I only own two games for testing, so I couldn't catch all the possible variations the first time.

**Comment by luxox8** [comment]
I understand you a lot :P

is there a way for obtain a start address manually meanwhile? based on the index section?

**Comment by maxton** [comment]
You could probably figure it out by following the documentation I wrote [here][1], the start address is calculated by the block size times the first direct block value of the file's inode. If the file is fragmented then things are trickier... the library doesn't even handle that case yet.

[1]: http://www.psdevwiki.com/ps4/PFS

**Comment by luxox8** [comment]
thanks for the info, is a little bit difficult figure out manually hahaha
